apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:latest
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: your_root_password
        - name: MYSQL_DATABASE
          value: your_database_name
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-data
      nodeSelector:
        app: "true"  # Bu satır, sadece "app=true" etiketine sahip node'larda çalışmasını sağlar