apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-slave
  template:
    metadata:
      labels:
        app: redis-slave
    spec:
      containers:
      - name: redis-slave
        image: redis:latest
        command: ["redis-server", "--slaveof", "redis-master", "6379"]
      nodeSelector:
        app: "true"  # Bu satır, sadece "app=true" etiketine sahip node'larda çalışmasını sağlar
