apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-master-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-master
  template:
    metadata:
      labels:
        app: redis-master
    spec:
      containers:
      - name: redis-master
        image: redis:latest
      nodeSelector:
        app: "true"  # Bu satır, sadece "app=true" etiketine sahip node'larda çalışmasını sağlar